CREATE OR REPLACE DATABASE DYNAMIC_TABLE_LAB;
USE DATABASE DYNAMIC_TABLE_LAB;
CREATE SCHEMA IF NOT EXISTS RETAIL;
USE SCHEMA RETAIL;

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_ID NUMBER,
    STORE_ID NUMBER,
    SALES_DATE DATE,
    NET_AMOUNT NUMBER(12,2)
);

INSERT INTO FACT_SALES VALUES
(1, 101, '2025-10-01', 500.00),
(2, 102, '2025-10-02', 1500.00),
(3, 103, '2025-10-03', 2500.00),
(4, 104, '2025-10-04', 3500.00),
(5, 105, '2025-10-05', 4500.00),
(6, 106, '2025-10-06', 5500.00);

CREATE OR REPLACE DYNAMIC TABLE DT_SALES_DAILY_SUMMARY
    TARGET_LAG = '1 MINUTE'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    STORE_ID,
    SALES_DATE,
    SUM(NET_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY STORE_ID, SALES_DATE;

SELECT * FROM DT_SALES_DAILY_SUMMARY

INSERT INTO FACT_SALES VALUES
(5,103, '2025-10-03', 500),
(6,106, '2025-10-06', 1500);

CREATE OR REPLACE DYNAMIC TABLE DT_SALES_DAILY_MANUAL
    TARGET_LAG = '1 HOUR'
    WAREHOUSE = COMPUTE_WH
    INITIALIZE = ON_SCHEDULE
AS
SELECT 
    STORE_ID,
    SALES_DATE,
    SUM(NET_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY STORE_ID, SALES_DATE;

ALTER DYNAMIC TABLE DT_SALES_DAILY_MANUAL REFRESH;

SELECT * FROM DT_SALES_DAILY_MANUAL;

--Scenario 3: Dynamic Table creation using multiple base tables with FULL REFRESH and INITIALIZE ON_CREATE

CREATE OR REPLACE TABLE DIM_STORE (
  STORE_KEY    NUMBER,
  STORE_NAME   STRING,
  CITY         STRING,
  STATE        STRING,
  REGION       STRING
);

INSERT INTO DIM_STORE VALUES
(101, 'Chroma City Mall', 'Mumbai', 'MH', 'West'),
(102, 'Chroma Downtown', 'Delhi', 'DL', 'North'),
(103, 'Chroma Infinity', 'Bangalore', 'KA', 'South');

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_KEY   NUMBER,
  PRODUCT_NAME  STRING,
  CATEGORY      STRING,
  SUBCATEGORY   STRING,
  BRAND         STRING,
  UNIT_PRICE    NUMBER(10,2)
);

INSERT INTO DIM_PRODUCT VALUES
(2001, 'Sony Bravia 55"', 'Electronics', 'Television', 'Sony', 55000.00),
(2002, 'Samsung Galaxy S24', 'Electronics', 'Mobile', 'Samsung', 85000.00),
(2003, 'LG Refrigerator 260L', 'Home Appliances', 'Refrigerator', 'LG', 28000.00),
(2004, 'Philips Mixer', 'Home Appliances', 'Kitchen', 'Philips', 5000.00);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY NUMBER,
  FIRST_NAME   STRING,
  LAST_NAME    STRING,
  GENDER       STRING,
  CITY         STRING,
  STATE        STRING
);

INSERT INTO DIM_CUSTOMER VALUES
(501, 'Amit', 'Kumar', 'M', 'Delhi', 'DL'),
(502, 'Priya', 'Sharma', 'F', 'Mumbai', 'MH'),
(503, 'Ravi', 'Nair', 'M', 'Bangalore', 'KA'),
(504, 'Sneha', 'Patel', 'F', 'Ahmedabad', 'GJ');

CREATE OR REPLACE TABLE FACT_SALES (
  SALES_ID     NUMBER,
  SALES_DATE   DATE,
  STORE_KEY    NUMBER,
  PRODUCT_KEY  NUMBER,
  CUSTOMER_KEY NUMBER,
  NET_AMOUNT   NUMBER(12,2)
);

INSERT INTO FACT_SALES VALUES
(1, '2025-10-10', 101, 2001, 501, 55000.00),
(2, '2025-10-10', 102, 2002, 502, 85000.00),
(3, '2025-10-11', 101, 2003, 503, 28000.00),
(4, '2025-10-11', 103, 2004, 504, 5000.00),
(5, '2025-10-12', 101, 2001, 501, 56000.00),
(6, '2025-10-12', 103, 2003, 502, 29000.00);


CREATE OR REPLACE DYNAMIC TABLE DT_DAILY_STORE_CATEGORY_SALES
    TARGET_LAG = '10 MINUTE'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = AUTO
AS
SELECT 
    fs.SALES_DATE,
    ds.STORE_NAME,
    ds.CITY AS STORE_CITY,
    ds.STATE AS STORE_STATE,
    dp.CATEGORY,
    dp.SUBCATEGORY ,
    dp.BRAND,
    SUM(fs.NET_AMOUNT) AS TOTAL_NET_SALES,
    COUNT(DISTINCT fs.SALES_ID) AS TRANSACTION_COUNT,
    COUNT(DISTINCT fs.CUSTOMER_KEY) AS UNIQUE_CUSTOMERS
FROM FACT_SALES fs
    JOIN DIM_STORE ds on fs.STORE_KEY = ds.STORE_KEY
    JOIN DIM_PRODUCT dp ON fs.PRODUCT_KEY = dp.PRODUCT_KEY
    JOIN DIM_CUSTOMER dc ON fs.CUSTOMER_KEY = dc.CUSTOMER_KEY
GROUP BY 1,2,3,4,5,6,7;

SELECT * FROM DT_DAILY_STORE_CATEGORY_SALES ORDER BY SALES_DATE, STORE_NAME;

--SCD2 one type of example 
    
CREATE OR REPLACE TABLE CUSTOMER_STG (
  CUSTOMER_ID INT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  EMAIL VARCHAR(100),
  PHONE_NUMBER VARCHAR(15),
  FULL_ADDRESS VARCHAR(365),
  LOAD_DATE DATE
);

INSERT INTO CUSTOMER_STG
VALUES
(1, 'Michael', 'Doe', 'mike@example.com', '1234567890', '123 Main St, New York, NY, 10001', '2024-01-01'),
(2, 'Rahul', 'Jain', 'rk@example.com', '0987654321', 'Bangalore, India', '2024-01-01'),
(3, 'John', 'Doe', 'john.doe2@example.com', '1234567890', '789 Broadway St, New York, NY, 10002', '2024-01-01'),
(4, 'Josh', 'Brown', 'josh@example.com', '1122334455', '321 Elm St, Chicago, IL, 60601', '2024-01-01'),
(5, 'Kim', 'kate', 'kate@example.com', '0987654322', '654 Oak St, San Francisco, CA, 94102', '2024-01-01');

CREATE OR REPLACE DYNAMIC TABLE CUSTOMER_MAIN
  TARGET_LAG='1 MINUTE'
  WAREHOUSE=COMPUTE_WH
AS
SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    FULL_ADDRESS,
    LOAD_DATE,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY LOAD_DATE DESC) rnm,
    CASE WHEN rnm=1 THEN 'Y' ELSE 'N' END ACTION_CD,
    CASE WHEN rnm=1 THEN NULL ELSE CURRENT_DATE() END LOAD_END_DATE
FROM CUSTOMER_STG;

ALTER DYNAMIC TABLE CUSTOMER_MAIN REFRESH;
SELECT * EXCLUDE (FULL_ADDRESS) FROM CUSTOMER_MAIN;
SELECT * EXCLUDE (FULL_ADDRESS) FROM CUSTOMER_MAIN WHERE CUSTOMER_ID=1;

Use case to demonstrate the kind of transaction with UPDATE --
SELECT * FROM CUSTOMER_STG WHERE CUSTOMER_ID=1;
DELETE FROM CUSTOMER_STG WHERE CUSTOMER_ID=1;

-- The base table 
INSERT INTO CUSTOMER_STG 
VALUES
(2, 'Rahul', 'Jain', 'newrk@example.com', '0987654321', 'Bangalore, India', '2024-01-02'); --> This is the new insert in staging table.
SELECT * FROM CUSTOMER_STG WHERE CUSTOMER_ID=2;
ALTER DYNAMIC TABLE CUSTOMER_MAIN REFRESH;

SELECT * FROM CUSTOMER_MAIN

































