CREATE OR REPLACE DATABASE HR_DEMO;
CREATE OR REPLACE SCHEMA HR_DEMO_PUBLIC;
USE SCHEMA HR_DEMO.PUBLIC;


CREATE OR REPLACE ROLE DATA_ENGINEER;
CREATE OR REPLACE ROLE HR_ADMIN;
CREATE OR REPLACE ROLE HR_MANAGER;
CREATE OR REPLACE ROLE HR_PAYROLL;
CREATE OR REPLACE ROLE HR_ANALYST;
CREATE OR REPLACE ROLE HR_RESTRICTED;

-- Role hierarchy
GRANT ROLE HR_RESTRICTED TO ROLE HR_ANALYST;
GRANT ROLE HR_ANALYST TO ROLE HR_PAYROLL;
GRANT ROLE HR_PAYROLL TO ROLE HR_MANAGER;
GRANT ROLE HR_MANAGER TO ROLE HR_ADMIN;

GRANT ROLE HR_RESTRICTED TO ROLE DATA_ENGINEER;
GRANT ROLE HR_ANALYST TO ROLE DATA_ENGINEER;
GRANT ROLE HR_PAYROLL TO ROLE DATA_ENGINEER;
GRANT ROLE HR_MANAGER TO ROLE DATA_ENGINEER;
GRANT ROLE HR_ADMIN TO ROLE DATA_ENGINEER;

GRANT ROLE DATA_ENGINEER TO ROLE SECURITYADMIN;

USE ROLE USERADMIN;

CREATE OR REPLACE USER data_engineer_demo
  PASSWORD = 'DataEng#2025'
  LOGIN_NAME = 'data_engineer_demo'
  DEFAULT_ROLE = DATA_ENGINEER
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DATA_ENGINEER TO USER data_engineer_demo;

CREATE OR REPLACE USER hr_admin_demo
  PASSWORD = 'HrAdmin#2025'
  LOGIN_NAME = 'hr_admin_demo'
  DEFAULT_ROLE = HR_ADMIN
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE HR_ADMIN TO USER hr_admin_demo;

CREATE OR REPLACE USER hr_manager_demo
  PASSWORD = 'HrManager#2025'
  LOGIN_NAME = 'hr_manager_demo'
  DEFAULT_ROLE = HR_MANAGER
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE HR_MANAGER TO USER hr_manager_demo;

CREATE OR REPLACE USER hr_payroll_demo
  PASSWORD = 'HrPayroll#2025'
  LOGIN_NAME = 'hr_payroll_demo'
  DEFAULT_ROLE = HR_PAYROLL
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE HR_PAYROLL TO USER hr_payroll_demo;

CREATE OR REPLACE USER hr_analyst_demo
  PASSWORD = 'HrAnalyst#2025'
  LOGIN_NAME = 'hr_analyst_demo'
  DEFAULT_ROLE = HR_ANALYST
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE HR_ANALYST TO USER hr_analyst_demo;

CREATE OR REPLACE USER hr_restricted_demo
  PASSWORD = 'HrRestricted#2025'
  LOGIN_NAME = 'hr_restricted_demo'
  DEFAULT_ROLE = HR_RESTRICTED
  DEFAULT_WAREHOUSE = HR_DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE HR_RESTRICTED TO USER hr_restricted_demo;

GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_RESTRICTED;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_RESTRICTED;

GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_ADMIN;
GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_MANAGER;
GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_PAYROLL;
GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_ANALYST;
GRANT USAGE ON DATABASE HR_DEMO TO ROLE HR_RESTRICTED;

GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ADMIN;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_MANAGER;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_PAYROLL;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ANALYST;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE HR_RESTRICTED;

GRANT SELECT ON ALL TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_MANAGER;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_PAYROLL;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_RESTRICTED;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_MANAGER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_PAYROLL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HR_DEMO.PUBLIC TO ROLE HR_RESTRICTED;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_MANAGER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_PAYROLL;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_RESTRICTED;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER;

GRANT USAGE ON DATABASE HR_DEMO TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA HR_DEMO.PUBLIC TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE MASKING POLICY ON SCHEMA HR_DEMO.PUBLIC TO ROLE DATA_ENGINEER;

USE ROLE DATA_ENGINEER;	

-- Sample HR tables
CREATE OR REPLACE TABLE EMPLOYEES (
  EMPLOYEE_ID INT,
  FULL_NAME STRING,
  SSN STRING,
  DOB DATE,
  EMAIL STRING,
  PHONE STRING,
  ADDRESS STRING,
  DEPARTMENT STRING
);

CREATE OR REPLACE TABLE PAYROLL (
  EMPLOYEE_ID INT,
  SALARY NUMBER(10,2),
  BONUS NUMBER(10,2)
);

CREATE OR REPLACE TABLE BENEFITS (
  EMPLOYEE_ID INT,
  INSURANCE_NUMBER STRING,
  PROVIDER STRING
);

INSERT INTO EMPLOYEES VALUES
(1,'Alice Smith','111-22-3333','1985-06-15','alice.smith@example.com','+1-555-1111','123 Maple St, City','HR'),
(2,'Bob Jones','222-33-4444','1990-11-22','bob.jones@example.com','+1-555-2222','234 Oak Ave, City','Finance'),
(3,'Carol Lee','333-44-5555','1979-02-09','carol.lee@example.com','+1-555-3333','345 Pine Rd, City','Engineering');

INSERT INTO PAYROLL VALUES (1,120000,5000),(2,90000,2000),(3,150000,10000);
INSERT INTO BENEFITS VALUES (1,'INS-3456-998','BlueCross'),(2,'INS-8899-111','Aetna'),(3,'INS-7777-222','Cigna');

--SSN
CREATE OR REPLACE MASKING POLICY MASK_SSN_REGEX
AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('HR_ADMIN','HR_MANAGER') THEN VAL
        WHEN CURRENT_ROLE() = 'HR_PAYROLL' THEN REGEXP_REPLACE(VAL,'(\\d{3}-)\\d{2}-(\\d{4})', '\\1XX-\\2')
        WHEN CURRENT_ROLE() = 'HR_ANALYST' THEN REGEXP_REPLACE(VAL, '\\d', 'X')
        ELSE 'REDACTED'
  END;

-- EMAIL
CREATE OR REPLACE MASKING POLICY MASK_EMAIL_REGEX
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('HR_ADMIN','HR_MANAGER') THEN VAL
    WHEN CURRENT_ROLE() = 'HR_ANALYST' THEN REGEXP_REPLACE(VAL, '(@.*)', '@****')
    ELSE 'hidden@example.com'
  END;

-- PHONE
CREATE OR REPLACE MASKING POLICY MASK_PHONE_REGEX
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('HR_ADMIN','HR_MANAGER') THEN VAL
    WHEN CURRENT_ROLE() = 'HR_ANALYST' THEN REGEXP_REPLACE(VAL, '(\\d{3}-\\d{4})$', '****')
    ELSE 'XXX-XXXX'
  END;

-- SALARY
CREATE OR REPLACE MASKING POLICY MASK_SALARY_COMPLEX
AS (VAL NUMBER) RETURNS NUMBER ->
  CASE
    WHEN CURRENT_ROLE() IN ('HR_ADMIN','HR_MANAGER','HR_PAYROLL') THEN VAL
    WHEN CURRENT_ROLE() = 'HR_ANALYST' THEN
        CASE
          WHEN VAL < 100000 THEN 99999       -- represent "<100K"
          WHEN VAL < 150000 THEN 149999      -- represent "100K–150K"
          ELSE 150001                        -- represent ">150K"
        END
    ELSE NULL
  END;

-- INSURANCE_NUMBER
CREATE OR REPLACE MASKING POLICY MASK_INSURANCE_REGEX
AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('HR_ADMIN','HR_MANAGER') THEN VAL
    WHEN CURRENT_ROLE() = 'HR_ANALYST' THEN REGEXP_REPLACE(VAL, '(INS-)\\d{4}-(\\d+)', '\\1XXXX-\\2')
    ELSE 'INS-XXXX-XXX'
  END;

  -- Attach policies to columns
ALTER TABLE EMPLOYEES ALTER COLUMN SSN SET MASKING POLICY MASK_SSN_REGEX;
ALTER TABLE EMPLOYEES ALTER COLUMN EMAIL SET MASKING POLICY MASK_EMAIL_REGEX;
ALTER TABLE EMPLOYEES ALTER COLUMN PHONE SET MASKING POLICY MASK_PHONE_REGEX;
ALTER TABLE PAYROLL ALTER COLUMN SALARY SET MASKING POLICY MASK_SALARY_COMPLEX;
ALTER TABLE BENEFITS ALTER COLUMN INSURANCE_NUMBER SET MASKING POLICY MASK_INSURANCE_REGEX;

USE ROLE HR_MANAGER;
SELECT CURRENT_ROLE() AS ACTIVE_ROLE;

SELECT E.FULL_NAME, E.SSN, E.EMAIL, P.SALARY, B.INSURANCE_NUMBER
FROM HR_DEMO.PUBLIC.EMPLOYEES E
JOIN HR_DEMO.PUBLIC.PAYROLL P ON E.EMPLOYEE_ID = P.EMPLOYEE_ID
JOIN HR_DEMO.PUBLIC.BENEFITS B ON E.EMPLOYEE_ID = B.EMPLOYEE_ID


USE ROLE HR_PAYROLL;
SELECT CURRENT_ROLE() AS ACTIVE_ROLE;
SELECT E.FULL_NAME, E.SSN, P.SALARY
FROM EMPLOYEES E
JOIN PAYROLL P USING (EMPLOYEE_ID);

USE ROLE HR_ANALYST;
SELECT CURRENT_ROLE() AS ACTIVE_ROLE;
SELECT E.FULL_NAME, E.SSN, E.EMAIL, E.PHONE, P.SALARY, B.INSURANCE_NUMBER
FROM EMPLOYEES E
JOIN PAYROLL P USING (EMPLOYEE_ID)
JOIN BENEFITS B USING (EMPLOYEE_ID);

USE ROLE HR_RESTRICTED;
SELECT CURRENT_ROLE() AS ACTIVE_ROLE;
SELECT * FROM EMPLOYEES;












