create or replace database STREAM_DEMO_DB;

USE DATABASE STREAM_DEMO_DB;

CREATE OR REPLACE SCHEMA STREAM_ZONE;

CREATE OR REPLACE SCHEMA RAW_TBLS;

CREATE OR REPLACE SCHEMA CURATED_TBLS;

CREATE OR REPLACE TABLE RAW_TBLS.STG_PROJECTS
(
  PROJ_ID INT,
  PROJ_NAME VARCHAR(50),
  BUDGET FLOAT,
  TEAM_SIZE INT,
  DOMAIN VARCHAR(20),
  CITY VARCHAR(30)
)

CREATE OR REPLACE STREAM STREAM_ZONE.STREAM_PROJECTS
ON TABLE RAW_TBLS.STG_PROJECTS;

SELECT * FROM STREAM_ZONE.STREAM_PROJECTS;

CREATE OR REPLACE TABLE CURATED_TBLS.PROJECTS
(
    PROJ_ID INT,
    PROJ_NAME VARCHAR(50),
    BUDGET FLOAT,
    TEAM_SIZE INT,
    DOMAIN VARCHAR(25),
    CITY VARCHAR(30),
    CREATED_DT DATE,
    UPDATED_DT DATE
);

INSERT INTO RAW_TBLS.STG_PROJECTS
(PROJ_ID, PROJ_NAME, BUDGET, TEAM_SIZE, DOMAIN, CITY)
VALUES
(101, 'Healthcare Analytics', 1200000.50, 12, 'Healthcare', 'Hyderabad'),
(102, 'Retail Recommendation', 850000.00, 10, 'Retail', 'Bangalore'),
(103, 'Fraud Detection System', 2000000.75, 18, 'Finance', 'Mumbai'),
(104, 'Customer 360 Platform', 1500000.00, 15, 'CRM', 'Chennai'),
(105, 'IoT Sensor Monitoring', 950000.25, 9, 'IoT', 'Pune'),
(106, 'Supply Chain Optimization', 1800000.00, 14, 'Logistics', 'Delhi'),
(107, 'E-Commerce Data Lake', 2200000.00, 20, 'E-Commerce', 'Bangalore'),
(108, 'Marketing Attribution', 700000.00, 8, 'Marketing', 'Hyderabad'),
(109, 'Cloud Migration', 3000000.00, 25, 'Cloud', 'Noida'),
(110, 'HR Analytics Dashboard', 500000.00, 6, 'HR', 'Chennai'),
(111, 'AI Chatbot Platform', 1250000.00, 11, 'AI', 'Bangalore'),
(112, 'Banking Risk Engine', 2750000.50, 22, 'Finance', 'Mumbai'),
(113, 'Telecom Usage Analytics', 1600000.75, 13, 'Telecom', 'Gurgaon'),
(114, 'Smart City Initiative', 3500000.00, 30, 'Government', 'Delhi'),
(115, 'EdTech Learning Platform', 900000.00, 9, 'Education', 'Hyderabad');

INSERT INTO CURATED_TBLS.PROJECTS 
( PROJ_ID,PROJ_NAME,BUDGET,TEAM_SIZE,DOMAIN,CITY,CREATED_DT,UPDATED_DT )
SELECT PROJ_ID, PROJ_NAME, BUDGET ,TEAM_SIZE, DOMAIN, CITY, CURRENT_DATE, NULL
FROM STREAM_ZONE.STREAM_PROJECTS
WHERE METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = FALSE;

select * from CURATED_TBLS.PROJECTS 


UPDATE RAW_TBLS.STG_PROJECTS SET BUDGET = 46000000 WHERE PROJ_ID = 102;

MERGE INTO CURATED_TBLS.PROJECTS T
USING STREAM_ZONE.STREAM_PROJECTS S
ON T.PROJ_ID = S.PROJ_ID
WHEN MATCHED 
  AND METADATA$ACTION = 'INSERT'
  AND METADATA$ISUPDATE = 'TRUE'
THEN UPDATE 
    SET T.PROJ_NAME = S.PROJ_NAME,
        T.BUDGET = S.BUDGET,
        T.TEAM_SIZE = S.TEAM_SIZE,
        T.DOMAIN = S.DOMAIN,
        T.CITY = S.CITY, 
        T.UPDATED_DT = CURRENT_DATE;

SELECT * FROM CURATED_TBLS.PROJECTS

DELETE FROM RAW_TBLS.STG_PROJECTS WHERE PROJ_ID = 103 AND 104

MERGE INTO CURATED_TBLS.PROJECTS T
USING STREAM_ZONE.STREAM_PROJECTS S
ON T.PROJ_ID = S.PROJ_ID
WHEN MATCHED 
    AND METADATA$ACTION = 'DELETE'
    AND METADATA$UPDATE = 'FALSE'
THEN DELETE;

---- TASKS

CREATE OR REPLACE TASK TASK_PROJECTS_LOAD
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTES'
    WHEN SYSTEM$STREAM_HAS_DATA('STREAM_ZONE.STREAM_PROJECTS')
AS
MERGE INTO CURATED_TBLS.PROJECTS T
USING STREAM_ZONE.STREAM_PROJECTS S
 ON T.PROJ_ID = S.PROJ_ID
WHEN MATCHED
    AND S.METADATA$ACTION = 'DELETE'
    AND S.METADATA$ISUPDATE = FALSE
    THEN DELETE
WHEN MATCHED 
    AND S.METADATA$ACTION = 'INSERT'
    AND S.METADATA$ISUPDATE = TRUE
    THEN UPDATE 
    SET T.PROJ_NAME = S.PROJ_NAME,
        T.BUDGET = S.BUDGET,
        T.TEAM_SIZE = S.TEAM_SIZE,
        T.DOMAIN = S.DOMAIN,
        T.CITY = S.CITY, 
        T.UPDATED_DT = CURRENT_DATE
WHEN NOT MATCHED 
    AND S.METADATA$ACTION = 'INSERT'
    AND S.METADATA$ISUPDATE = FALSE
    THEN INSERT (PROJ_ID, PROJ_NAME, BUDGET, TEAM_SIZE, DOMAIN, CITY,  CREATED_DT, UPDATED_DT)
         VALUES (S.PROJ_ID, S.PROJ_NAME, S.BUDGET, S.TEAM_SIZE, S.DOMAIN, S.CITY, CURRENT_DATE, NULL);


ALTER TASK TASK_PROJECTS_LOAD RESUME;
EXECUTE TASK TASK_PROJECTS_LOAD;

INSERT INTO RAW_TBLS.STG_PROJECTS VALUES
(120, 'GRAVITY', 700000, 10, 'RETAIL', 'PUNE'),
(121, 'HELIOS', 650000, 14, 'FINTECH', 'BANGLORE');

------TASKS IN SPECIFIC ONLY 
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE TASKS_DEMO_DB;
USE DATABASE TASKS_DEMO_DB;

CREATE OR REPLACE SCHEMA TASKS_DEMO_SCHEMA;
USE SCHEMA TASKS_DEMO_SCHEMA;

-- Raw ingestion table
CREATE OR REPLACE TABLE RAW_SALES (
    SALE_ID INT,
    REGION STRING,
    AMOUNT FLOAT,
    SALE_DATE DATE
);

-- Curated table for cleaned data
CREATE OR REPLACE TABLE CLEAN_SALES (
    SALE_ID INT,
    REGION STRING,
    AMOUNT FLOAT,
    SALE_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP
);

-- Aggregated summary table
CREATE OR REPLACE TABLE SALES_SUMMARY (
    REGION STRING,
    TOTAL_SALES FLOAT,
    LOAD_TIMESTAMP TIMESTAMP
);

-- A task that runs every 1 minute
CREATE OR REPLACE TASK TASK_LOAD_RAW_SALES
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
AS
INSERT INTO RAW_SALES
SELECT SEQ8(), REGION, UNIFORM(100,1000,RANDOM()), CURRENT_DATE
FROM (SELECT COLUMN1 AS REGION FROM VALUES ('NORTH'),('SOUTH'),('EAST'),('WEST'));
alter task TASK_LOAD_RAW_SALES resume;
select * from TASKS_DEMO_DB.TASKS_DEMO_SCHEMA.RAW_SALES;


GRANT USAGE
ON WAREHOUSE COMPUTE_WH
TO ROLE SYSADMIN;

CREATE OR REPLACE TASK TASK_PARENT_LOAD
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '10 minute'
AS
INSERT INTO RAW_SALES
SELECT SEQ8(), REGION, UNIFORM(100,1000,RANDOM()), CURRENT_DATE
FROM (SELECT COLUMN1 AS REGION FROM VALUES ('NORTH'),('SOUTH'),('EAST'),('WEST'));

CREATE OR REPLACE TASK TASK_CHILD_CLEAN
    WAREHOUSE = COMPUTE_WH
    AFTER TASK_PARENT_LOAD
AS
INSERT INTO CLEAN_SALES
SELECT *, CURRENT_TIMESTAMP()
FROM RAW_SALES
WHERE SALE_DATE = CURRENT_DATE;

CREATE OR REPLACE TASK TASK_CHILD_AGGREGATE
    WAREHOUSE = COMPUTE_WH
    AFTER TASK_CHILD_CLEAN
AS
INSERT INTO SALES_SUMMARY
SELECT REGION, SUM(AMOUNT), CURRENT_TIMESTAMP()
FROM CLEAN_SALES
GROUP BY REGION;





